### ISSUE TITLE
Day One: Learn Hub Development

### ISSUE THREAD

**Issue by haikalsamari** [wsomad/openlearnhub#1]
### **Description**

We need to complete several tasks for pre-development stage.

### **Task**

- [x] Initialize GitHub repo.
- [x] Finalize tech stacks used.
- [x] Identify what kind of data, components involved.
- [x] Create a draft for ERD.
